@startuml
skinparam legendFontSize 18
skinparam usecaseFontSize 18
skinparam usecaseFontColor #fff
skinparam usecaseArrowFontSize 18
skinparam usecaseBackgroundColor #2c95dd

(Система) as Система #696767
(Архитектура) as Архитектура #696767
(Проектирование) as Проектирование #696767
(Программный Продукт) as "Программный Продукт" #696767
(Модель Жизненного Цикла) as "Модель Жизненного Цикла" #696767

(Программный Продукт) --> (Система): NT
(Система) -> (Программный Продукт): BT
(Процесс) --> (Система): NTP
(Программный Модуль) --> (Программная Составная Часть): NTP
(Система) --> (Программная Составная Часть): UF
(Программная Составная Часть) --> (Программный Продукт): NTP
(Архитектура) ---> (Программный Продукт): NTP
(Архитектурный Срез) --> (Оценивание): NTG
(Оценивание) --> (Жизненный Цикл): NTP
(Модель Жизненного Цикла) --> (Жизненный Цикл): BT
(Жизненный Цикл) --> (Модель Жизненного Цикла): NT
(Оценивание) --> (Проектирование): RT
(Проектирование) --> (Жизненный Цикл): NTP
(Архитектура) --> (Архитектурный Срез): NT
(Архитектурный Срез) --> (Архитектура): BT
(Архитектурная Позиция) --> (Архитектура): NTP
(Проектирование) --> (Архитектурная Позиция): NTG
(Проектирование) --> (Техническое Задание): RT
(Проектирование) --> (Разработчик): RT
(Разработчик) --> (Проектирование): RT
(Разработчик) --> (Архитектурный Инструментарий): RT
(Разработчик) --> (Техническое Задание): RT

legend right
  <b>BT</b> - связь с родительским элементом
  <b>NT</b> - связь с дочерним элементом
  <b>UF</b> - эквивалентность
  <b>RT</b> - ассоциация
  <b>NTP</b> - является частью
  <b>NTG</b> - является видом
endlegend

@enduml